#!/usr/bin/perl

use strict;
use warnings;

open(LINE, $ARGV[0]);

my %hash=(
1=>1,
2=>1,
3=>1,
4=>1,
5=>1,
6=>1,
7=>1,
8=>1,
9=>1,
10=>1,
11=>1,
12=>1,
13=>1,
14=>1,
15=>1,
16=>1,
17=>1,
18=>1,
19=>1,
20=>1,
21=>1,
22=>1,
"X"=>1,
"Y"=>1);

while (my $line = <LINE>){
	chomp $line;
	my @a=split(/\t/,$line);
	my $alt;
	if($a[0]=~/chr(\w+)/){$alt=$1;}
	else{$alt=$a[0];}
	
	if( $hash{$a[0]} || $hash{$alt}){
	if ($a[1]<$a[2]){
		print $line,"\n";
	}
	}
}
